theme: jekyll-theme-cayman
title: sttp.goapi
description: Streaming Telemetry Transport Protocol GO API
github:
  repository_name: sttp.goapi
  owner_url: https://www.gridprotectionalliance.org
  owner_name: Grid Protection Alliance
plugins:
  - jemoji
